Controllers films users
Michail-A/java-filmorate pull request #5
Opened 2023-05-14 19:18 UTC by Michail-A

2023-05-15 16:46 UTC, NikolaiDem requested changes

2023-05-15 16:46 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/Exceptions/ValidationException.java
> +package ru.yandex.practicum.filmorate.controller.Exceptions;
Пакеты лучше именовать в нижнем регистре, чтобы не путать их с классами

2023-05-15 16:46 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/Exceptions/ValidationException.java
> +public class ValidationException extends Exception {
Лучше отнаследовать от RuntimeException, восстановление после исключения не планируется )

2023-05-15 16:46 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank()) {
Все непримитивные поля еще нужно проверить на null

2023-05-15 16:46 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
LocalDate.of(1895, 12, 28) лучше вынести в константы

2023-05-15 16:46 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validate(Film film) throws ValidationException {
Валидации еще можно делать декларативно через аннотации, например,
https://www.baeldung.com/spring-boot-bean-validation

2023-05-15 16:46 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null) {
Еще нужна проверка на ""

2023-05-15 16:46 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail().isEmpty() || !user.getEmail().contains("@")) {
Все непримитивные поля еще нужно проверить на null

2023-05-15 16:46 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void validate(User user) throws ValidationException {
Валидации еще можно делать декларативно через аннотации, например,
https://www.baeldung.com/spring-boot-bean-validation

2023-05-15 16:46 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().isEmpty() || user.getLogin().isBlank()) {
Еще логин не может содержать пробелы

2023-05-16 22:40 UTC, NikolaiDem requested changes

2023-05-16 22:40 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank() || film.getName() == null) {
Первыми должны выполняться проверки на null, иначе в них нет смысла)

2023-05-16 22:40 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail().isBlank() || !user.getEmail().contains("@") || user.getEmail() == null) {
Первыми должны выполняться проверки на null, иначе в них нет смысла)

2023-05-16 22:40 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private LocalDate minDate = LocalDate.of(1895, 12, 28);
Константу можно сделать еще static final MIN_DATE

2023-05-16 23:24 UTC, Michail-A commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private LocalDate minDate = LocalDate.of(1895, 12, 28);
Тесты на гите не пропускают название "MIN_DATE"

2023-05-17 09:41 UTC, NikolaiDem approved these changes

2023-05-19 10:04 UTC, merged