Add friends likes
Michail-A/java-filmorate pull request #6
Opened 2023-05-21 06:35 UTC by Michail-A

2023-05-21 20:57 UTC, NikolaiDem requested changes

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Film addFilm(@RequestBody Film film) throws ValidationException {
throws ValidationException не нужен, потому что исключение непроверяемое

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Film updateFilm(@RequestBody Film film) throws ValidationException {
throws ValidationException не нужен, потому что исключение непроверяемое

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @RestController("/films")
films нужно поместить в 
@RequestMapping(path = "/films")
и удалить из методов

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  @RestController("/users")
users нужно поместить в
@RequestMapping(path = "/users")
и удалить из методов

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public User addUser(@RequestBody User user) throws ValidationException {
throws ValidationException не нужен, потому что исключение непроверяемое

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public User updateUser(@RequestBody User user) throws ValidationException {
throws ValidationException не нужен, потому что исключение непроверяемое

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(InMemoryFilmStorage filmStorage, FilmService filmService) {
Контроллер должен зависеть только от интерфейсов репозитория и сервиса

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(InMemoryUserStorage userStorage, UserService userService) {
Контроллер должен зависеть только от интерфейсов репозитория и сервиса

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/exceptions/ErrorHandler.java
> +    public Map<String, String> handleValidationException(final ValidationException e) {
Чтобы расследовать причины исключения, лучше залогировать его детали e.getMessage(). Можно вернуть его и в ответе.
Аналогично для остальных методов.

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Set<Integer> likes = new HashSet<>();
почему public?

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public Set<Integer> friends = new HashSet<>();
почему public?

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage filmStorage) {
Сервис не должен зависеть от реализации репозитория, только от интерфейса, чтобы не приходилось изменять сервис при изменении репозитория

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage userStorage) {
Сервис не должен зависеть от реализации репозитория, только от интерфейса, чтобы не приходилось изменять сервис при изменении репозитория

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!film.getLikes().contains(userId)) {
Метод проверки лайка лучше добавить в Film

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new RuntimeException();
Пустые и при этом общие исключения бросать нехорошо, потому что никаких следов к выяснению причины нет ) Создать кастомное непроверяемое исключение и добавить детали исключения

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new RuntimeException();
Пустые и при этом общие исключения бросать нехорошо, потому что никаких следов к выяснению причины нет ) Создать кастомное непроверяемое исключение и добавить детали исключения

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new RuntimeException("Такого фильма нет");
Сделать собственное исключение и выбросить его, в сообщение добавить некоторые детали запроса, например id фильма

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new RuntimeException();
Пустые и при этом общие исключения бросать нехорошо, потому что никаких следов к выяснению причины нет ) Создать кастомное непроверяемое исключение и добавить детали исключения

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new RuntimeException();
Пустые и при этом общие исключения бросать нехорошо, потому что никаких следов к выяснению причины нет ) Создать кастомное непроверяемое исключение и добавить детали исключения

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new RuntimeException("Такого пользователя нет");
Сделать собственное исключение и выбросить его, в сообщение добавить некоторые детали запроса, например id юзера

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> films = filmStorage.getFilms();
Можно проще:
        return filmStorage.getFilms().stream()
                .sorted((o1, o2) -> o2.getLikes().size() - o1.getLikes().size())
                .limit(count)
                .collect(Collectors.toList());

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return "Пользователь " + userId + " удалил лайк фильму " + filmId;
Лучше сообщение поместить в лог

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return "Пользователь " + userId + " поставил лайк фильму " + filmId;
Лучше сообщение поместить в лог

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PutMapping("/films/{id}/like/{userId}")
Для Put методов лучше вернуть код 204, а message записать в лог
@ResponseStatus(code = HttpStatus.NO_CONTENT)

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @DeleteMapping("/films/{id}/like/{userId}")
Для Put методов лучше вернуть код 204, а message записать в лог
@ResponseStatus(code = HttpStatus.NO_CONTENT)

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PutMapping("/users/{id}/friends/{friendId}")
Для Put методов лучше вернуть код 204, а message записать в лог
@ResponseStatus(code = HttpStatus.NO_CONTENT)

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @DeleteMapping("/users/{id}/friends/{friendId}")
Для Put методов лучше вернуть код 204, а message записать в лог
@ResponseStatus(code = HttpStatus.NO_CONTENT)

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userId + " добавил в друзья " + friendsId;
Лучше сообщение поместить в лог

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userId + " удалил из друзей " + friendsId;
Лучше сообщение поместить в лог

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getIdUsers().contains(userId) || !userStorage.getIdUsers().contains(friendsId)) {
Проверка лишняя. Репозиторий выбросит исключения, если пользователи будут отсутствовать

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            if (userStorage.getUserForId(friendsId).getFriends().contains(id)) {
userStorage.getUserForId(friendsId).getFriends() вынести в переменную, чтобы не обращаться к БД каждый раз

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> getCommonFriends(int userId, int friendsId) {
Попробовать реализовать через stream

2023-05-21 20:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Integer friendId : userStorage.getUserForId(id).friends) {
userStorage.getUserForId(id).friends вынести в переменную

2023-05-23 19:56 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(InMemoryFilmStorage filmStorage, FilmService filmService) {
Не исправлено.
public UserController(UserStorage userStorage, UserService userService) {
        this.userStorage = userStorage;
        this.userService = userService;
    }

2023-05-23 19:56 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(InMemoryUserStorage userStorage, UserService userService) {
Не исправлено.
public UserController(UserStorage userStorage, UserService userService) {
this.userStorage = userStorage;
this.userService = userService;
}

2023-05-23 19:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/exceptions/ErrorHandler.java
> +    public Map<String, String> handleValidationException(final ValidationException e) {
Не исправлено.
Добавить логирование

2023-05-23 19:59 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Set<Integer> likes = new HashSet<>();
Не исправлено

2023-05-23 19:59 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public Set<Integer> friends = new HashSet<>();
Не исправлено

2023-05-23 20:00 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage filmStorage) {
Не исправлено

2023-05-23 20:00 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage userStorage) {
Не исправлено

2023-05-23 20:01 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new RuntimeException();
Не исправлено

2023-05-23 20:02 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new RuntimeException();
Не исправлено

2023-05-23 20:02 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new RuntimeException("Такого фильма нет");
Не исправлено

2023-05-23 20:02 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new RuntimeException();
Не исправлено

2023-05-23 20:02 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new RuntimeException();
Не исправлено

2023-05-23 20:02 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new RuntimeException("Такого пользователя нет");
Не исправлено

2023-05-23 20:02 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> films = filmStorage.getFilms();
Не исправлено

2023-05-23 20:02 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return "Пользователь " + userId + " удалил лайк фильму " + filmId;
Не исправлено

2023-05-23 20:02 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return "Пользователь " + userId + " поставил лайк фильму " + filmId;
Не исправлено

2023-05-23 20:03 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PutMapping("/films/{id}/like/{userId}")
Не исправлено

2023-05-23 20:03 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @DeleteMapping("/films/{id}/like/{userId}")
Не исправлено

2023-05-23 20:03 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PutMapping("/users/{id}/friends/{friendId}")
Не исправлено

2023-05-23 20:03 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userId + " добавил в друзья " + friendsId;
Не исправлено

2023-05-23 20:03 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userId + " удалил из друзей " + friendsId;
Не исправлено

2023-05-23 20:03 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getIdUsers().contains(userId) || !userStorage.getIdUsers().contains(friendsId)) {
Не исправлено

2023-05-23 20:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            if (userStorage.getUserForId(friendsId).getFriends().contains(id)) {
Не исправлено

2023-05-23 20:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Integer friendId : userStorage.getUserForId(id).friends) {
Не исправлено

2023-05-23 20:05 UTC, NikolaiDem requested changes
Михаил, бОльшая часть замечаний не исправлена)

2023-05-23 22:09 UTC, Michail-A commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getIdUsers().contains(userId) || !userStorage.getIdUsers().contains(friendsId)) {
Репозиторий выбрасывает исключение при получении из него пользователей.  Без данной проверки не проходит тест на добавление в друзья к существующему пользователю несуществующего, так как список друзей хранится в виде id. Там тест на добавление пользователя с отрицательным id

2023-05-23 23:23 UTC, Michail-A commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @DeleteMapping("/users/{id}/friends/{friendId}")
в тестах постман проверяют код 200

2023-05-23 23:25 UTC, Michail-A commented
Запутался, куда смотреть, поэтому пропустил)

2023-05-26 17:59 UTC, merged